---
-
  become: true
  hosts: kube-master-01
  become_method: sudo
  become_user: root
  tasks:
    - name: Create /etc/apache2/sites-enabled/000-default.conf
      copy:
        dest: "/etc/apache2/sites-enabled/000-default.conf"
        content: |
          <VirtualHost *:80>
            RewriteEngine On
            RewriteCond %{HTTPS} !=on
            RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R=301,L]
          </virtualhost>
          <VirtualHost *:443>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html
            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
            SSLEngine on
            SSLCertificateFile /etc/apache2/certificate/apache-certificate.crt
            SSLCertificateKeyFile /etc/apache2/certificate/apache.key
          <Location />
            ProxyPass http://127.0.0.1:8001/
            ProxyPassReverse http://127.0.0.1:8001/
          </Location>
          </VirtualHost>

    - name: Restart apache2
      service:
        name: "apache2"
        state: "restarted"
        enabled: "yes"

    - name: Run kubectl proxy
      shell: kubectl proxy &
