---
-
  become: true
  hosts: kube-masters
  become_method: sudo
  become_user: root
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

      - name: set join command
        set_fact:
          join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: kube-nodes
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: join cluster
      shell: "{{ join_command_raw.stdout_lines[0] }}"
