---
-
  become: true
  hosts: primary-master
  become_method: sudo
  become_user: root
  tasks:
  - name: Install ingress-nginx
    shell: helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
  - name: Upgrade ingress-nginx for prometheus monitor
    shell: helm upgrade ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --set controller.metrics.enabled=true --set-string controller.podAnnotations."prometheus\.io/scrape"="true" --set-string controller.podAnnotations."prometheus\.io/port"="10254"
  - name: Install prometheus
    shell: kubectl apply --kustomize github.com/kubernetes/ingress-nginx/deploy/prometheus/

  - name: Create exec file port-forward-ingress
    copy:
        dest: "/usr/local/bin/port-forward-ingress"
        content: |
          #!/bin/bash
          sleep 60 # wait for running pod
          sudo kubectl port-forward -n ingress-nginx --address 192.168.1.111 svc/ingress-nginx-controller 80:80

  - name: Change file permissions port-forward-ingress
    ansible.builtin.file:
      path: /usr/local/bin/port-forward-ingress
      mode: '0777'

  - name: Create service port-forward-ingress
    copy:
        dest: "/etc/systemd/system/port-forward-ingress.service"
        content: |
          [Unit]
          Description=Kubernetes Proxy
          After=kubelet.service
          [Service]
          ExecStart=/usr/local/bin/port-forward-ingress
          Type=idle
          KillMode=process
          SyslogIdentifier=port-forward-ingress.service
          SyslogFacility=daemon
          Restart=on-failure
          [Install]
          WantedBy=multi-user.target

  - name: Start port-forward-ingress service
    service:
        name: "port-forward-ingress"
        state: "started"
        enabled: "yes"
