---
-
  become: true
  hosts: master01
  become_method: sudo
  become_user: root
  tasks:
  - name: Apply flannel
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: Waiting for 2 minutes until the pods start
    pause:
      minutes: 2

  - name: Stop systemd-udevd
    shell: systemctl stop systemd-udevd systemd-udevd-control.socket systemd-udevd-kernel.socket

  - name: Disabled systemd-udevd
    shell: systemctl disable systemd-udevd systemd-udevd-control.socket systemd-udevd-kernel.socket

  - name: Chmod systemd-udevd
    shell: chmod -x /usr/lib/systemd/systemd-udevd
