---
-
  become: true
  hosts: master01
  become_method: sudo
  become_user: root
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

-
  become: true
  hosts: worknodes
  become_method: sudo
  become_user: root
  tasks:
  - name: Change /etc/environment
    ansible.builtin.blockinfile:
      path: /etc/environment
      block: |
        KUBECONFIG=/etc/kubernetes/admin.conf
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: join cluster
    shell: "{{ hostvars['master01'].join_command }}"  # set primary master

  - name: Disabled systemd-udevd
    shell: systemctl disable systemd-udevd systemd-udevd-control.socket systemd-udevd-kernel.socket

  - name: Stop systemd-udevd
    shell: systemctl stop systemd-udevd systemd-udevd-control.socket systemd-udevd-kernel.socket

  - name: Chmod systemd-udevd
    shell: chmod -x /usr/lib/systemd/systemd-udevd
