
---
-
  hosts: localhost
  tasks:
    - name: PoweredON a virtual machine 
      community.vmware.vmware_guest:
        hostname: esxi.my
        username: root
        password: "!Passw0rd"
        validate_certs: False
        name: Ubuntu
        state: poweredoff
      delegate_to: localhost

