---
-
  become: true
  hosts: all
  become_method: sudo
  become_user: root
  tasks:
# ----- /etc/hosts ---------------------
  - name: Add host /etc/hosts
    copy:
      dest: "/etc/hosts"
      content: |
        127.0.0.1 localhost
        192.168.1.110 master01
        192.168.1.120 master02
        192.168.1.130 master03
        192.168.1.210 worknode01
        192.168.1.220 worknode02
        192.168.1.230 worknode03

  - name: Disabled AutoUpdate
    copy:
      dest: "/etc/apt/apt.conf.d/20auto-upgrades"
      content: |
        APT::Periodic::Update-Package-Lists "0";
        APT::Periodic::Unattended-Upgrade "0";

  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot:
