---
-
  become: true
  hosts: all
  become_method: sudo
  become_user: root
  tasks:
# ----- /etc/hosts ---------------------
  - name: Add host /etc/hosts
    copy:
      dest: "/etc/hosts"
      content: |
        127.0.0.1 localhost
        {{ hostvars['master01'].ansible_host }} {{ hostvars['master01'].inventory_hostname }}
        {{ hostvars['master02'].ansible_host }} {{ hostvars['master02'].inventory_hostname }}
        {{ hostvars['master03'].ansible_host }} {{ hostvars['master03'].inventory_hostname }}
        {{ hostvars['worknode01'].ansible_host }} {{ hostvars['worknode01'].inventory_hostname }}
        {{ hostvars['worknode02'].ansible_host }} {{ hostvars['worknode02'].inventory_hostname }}
        {{ hostvars['worknode03'].ansible_host }} {{ hostvars['worknode03'].inventory_hostname }}

  - name: Disabled AutoUpdate
    copy:
      dest: "/etc/apt/apt.conf.d/20auto-upgrades"
      content: |
        APT::Periodic::Update-Package-Lists "0";
        APT::Periodic::Unattended-Upgrade "0";

#  - name: Unconditionally reboot the machine with all defaults
#    ansible.builtin.reboot:
