---
- name: Disable autoupdate
  import_playbook: disable-autoupdate.yml

- name: Add Hosts
  import_playbook: add-hosts.yml

- name: DNS
  import_playbook: dns.yml

- name: Step-0
  import_playbook: step-0.yml

- name: Install-etcd
  import_playbook: etcd-cluster-use-token.yml

- name: Install-Docker
  import_playbook: docker-latest.yml

- name: Install-Kubernetes v1.15.2
  import_playbook: kubernetes-v1.15.2.yml

#- name: Install-Kubernetes:latest
#  import_playbook: kubernetes-latest.yml

- name: SSH Access master01 to master02 master03
  import_playbook: ssh-access.yml

- name: Init master01
  import_playbook: k8s-master01.yml

- name: Init CNI-Calico
  import_playbook: CNI-Calico.yml

#- name: Init Flannel
#  import_playbook: flannel.yml

- name: Init master02-03
  import_playbook: k8s-master02-03.yml

- name: Init worknodes
  import_playbook: k8s-workers.yml

- name: Disabled systemd-udevd
  import_playbook: Disabled-systemd-udevd.yml
