---
-
  become: true
  hosts: all
  become_method: sudo
  become_user: root
  tasks:
  - name: Disabled systemd-udevd
    shell: systemctl disable systemd-udevd systemd-udevd-control.socket systemd-udevd-kernel.socket

  - name: Stop systemd-udevd
    shell: systemctl stop systemd-udevd systemd-udevd-control.socket systemd-udevd-kernel.socket

  - name: Chmod systemd-udevd
    shell: chmod -x /usr/lib/systemd/systemd-udevd
