---
-
  become: true
  hosts: masters,worknodes
  become_method: sudo
  become_user: root
  tasks:
  - name: Docker login
    shell: docker login -u user -p 1234qwer registry.my
    ignore_errors: true

  - name: Docker rmi
    shell: docker rmi registry.my/image:test

  - name: Docker pull
    shell: docker pull registry.my/image:test
